// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  highlights: dynamic(() => import("./Highlights")),
  modules: dynamic(() => import("./Modules")),
};
